#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。
[project]
id = "Book-0225.EAP2"
name = "External_Audio_Processing2"
version = "0.0.29"

[build_group]
debug_group = "msbuild External_Audio_Processing2.slnx /p:Configuration=Debug /p:Platform=x64"
release_group = "msbuild External_Audio_Processing2.slnx /p:Configuration=Release /p:Platform=x64"

[artifacts.External_Audio_Processing2_aul2]
source = "English.External_Audio_Processing2.aul2"
enabled = true
destination = "Language/English.External_Audio_Processing2.aul2"

[artifacts.EAP2_obj2]
source = "@EAP2.obj2"
enabled = true
destination = "Script/EAP2/@EAP2.obj2"

[artifacts.External_Audio_Processing2_aux2]
enabled = true
destination = "Plugin/External_Audio_Processing2.aux2"

[artifacts.External_Audio_Processing2_aux2.profiles.debug]
build = { group = "debug_group"}
source = "x64/Debug/External_Audio_Processing2.aux2"

[artifacts.External_Audio_Processing2_aux2.profiles.release]
build = { group = "release_group"}
source = "x64/Release/External_Audio_Processing2.aux2"

[development]
aviutl2_version = "latest"

[preview]
aviutl2_version = "latest"

[release]
output_dir = "release"
package_template = "package.txt"
zip_name = "{name}"
profile = "release"
prebuild = "pwsh  -ExecutionPolicy Bypass -File sync_version.ps1"
package_name = "External Audio Processing 2"
package_information = "External Audio Processing 2 v{version} by BOOK25"